name = "infra-team-filecoin-snapshot-listing"
main = "src/index.ts"
compatibility_date = "2023-09-13"
logpush = true

# Default environment (production)
[env.production]
name = "infra-team-filecoin-snapshot-listing"
# Production-specific overrides can be added here

# R2 buckets for production environment
[[env.production.r2_buckets]]
binding = "SNAPSHOT_ARCHIVE"
bucket_name = "infra-team-filecoin-archive"

[[env.production.r2_buckets]]
binding = "FOREST_ARCHIVE"
bucket_name = "forest-archive"

[[env.production.r2_buckets]]
binding = "SNAPSHOT_ARCHIVE_V2"
bucket_name = "forest-snapshots-v2"

# Preview environment
[env.preview]
name = "filecoin-snapshot-listing-preview"

# R2 buckets for preview environment
[[env.preview.r2_buckets]]
binding = "SNAPSHOT_ARCHIVE"
bucket_name = "infra-team-filecoin-archive"

[[env.preview.r2_buckets]]
binding = "FOREST_ARCHIVE"
bucket_name = "forest-archive"

[[env.preview.r2_buckets]]
binding = "SNAPSHOT_ARCHIVE_V2"
bucket_name = "forest-snapshots-v2"

# Assets binding
[assets]
directory = "./public"
binding = "ASSETS"

# Routes - Production only
[[env.production.routes]]
pattern = "forest-archive.chainsafe.dev/*"
zone_name = "chainsafe.dev"

# Preview environment will use the default worker.dev subdomain
# No custom routes needed for preview

# Observability / logs
[observability.logs]
enabled = true
head_sampling_rate = 0.1

# Environment-specific configurations
[env.preview.observability.logs]
enabled = true
head_sampling_rate = 1.0  # Higher sampling for preview debugging
